### ISSUE TITLE
Is it possible to host this on GitHub?

### ISSUE THREAD

**Issue by jjculber** [phiresky/fbstats#1]
Is it possible to use GitHub Pages to host this? It's a static site, so that should be possible. It would be awesome if it prompted the user for an appid before starting, that way, we could all use the same hosted application. A small set of instructions on how to create a new app would be helpful before prompting the user to enter their appid. I created one, but I get an "Error 101: Invalid API key". This would make it really easy for new users to create a graph without hosting the code themselves. What do you think?

**Comment by phiresky** [comment]
I just created this.
http://tehdog.github.io/fbstats/
It should work, I also wrote a detailed guide in the readme.

**Comment by jjculber** [comment]
That was perfect! Thanks so much.
