### ISSUE TITLE
}ERR:no permission

### ISSUE THREAD

**Issue by grandmst** [phiresky/fbstats#5]
after not getting it working checking the diagnostics.html i get this 

}/me/permissions
{
   "data": [
      {
         "permission": "public_profile",
         "status": "granted"
      },
      {
         "permission": "read_mailbox",
         "status": "granted"
      }
   ]
}ERR:no permission

any idea why?

**Comment by phiresky** [comment]
Hi, could you tell me what API version you are using? When did you create the app on facebook?

**Comment by phiresky** [comment]
Also, what error did you get on the main page?

**Comment by grandmst** [comment]
hi, i was getting (could not access message data) on the index page, and the latest version of the API.

**Comment by phiresky** [comment]
I fixed that bug, you should now get the error `REST API is deprecated for versions v2.1 and higher`. I don't think it's possible to fix this currently, see #6.
